<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="3" total="5" passed="0">
    <reporter-output>
    </reporter-output>
    <suite name="Failed suite [Default Suite]" duration-ms="1" started-at="2021-03-10T06:44:44Z"
           finished-at="2021-03-10T06:44:44Z">
        <groups>
        </groups>
        <test name="API_AutoFramework_Demo(failed)" duration-ms="1" started-at="2021-03-10T06:44:44Z"
              finished-at="2021-03-10T06:44:44Z">
            <class name="com.qa.z_liuhaoqun_lenarn_canshu.ReRunFailedTestDemo">
                <test-method status="FAIL"
                             signature="test05()[pri:0, instance:com.qa.z_liuhaoqun_lenarn_canshu.ReRunFailedTestDemo@2ef5e5e3]"
                             name="test05" duration-ms="1" started-at="2021-03-10T06:44:44Z"
                             finished-at="2021-03-10T06:44:44Z">
                    <exception class="java.lang.AssertionError">
                        <message>
                            <![CDATA[expected [true] but found [false]]]>
                        </message>
                        <full-stacktrace>
                            <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.qa.z_liuhaoqun_lenarn_canshu.ReRunFailedTestDemo.test05(ReRunFailedTestDemo.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.qa.z_liuhaoqun_lenarn_canshu.a_first_ReRunTestNg.main(ReRunTestNg.java:30)
]]>
                        </full-stacktrace>
                    </exception> <!-- java.lang.AssertionError -->
                    <reporter-output>
                    </reporter-output>
                </test-method> <!-- test05 -->
                <test-method status="FAIL"
                             signature="test03()[pri:0, instance:com.qa.z_liuhaoqun_lenarn_canshu.ReRunFailedTestDemo@2ef5e5e3]"
                             name="test03" duration-ms="0" started-at="2021-03-10T06:44:44Z"
                             finished-at="2021-03-10T06:44:44Z">
                    <exception class="java.lang.AssertionError">
                        <message>
                            <![CDATA[expected [true] but found [false]]]>
                        </message>
                        <full-stacktrace>
                            <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.qa.z_liuhaoqun_lenarn_canshu.ReRunFailedTestDemo.test03(ReRunFailedTestDemo.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.qa.z_liuhaoqun_lenarn_canshu.a_first_ReRunTestNg.main(ReRunTestNg.java:30)
]]>
                        </full-stacktrace>
                    </exception> <!-- java.lang.AssertionError -->
                    <reporter-output>
                    </reporter-output>
                </test-method> <!-- test03 -->
            </class> <!-- com.qa.z_liuhaoqun_lenarn_canshu.ReRunFailedTestDemo -->
        </test> <!-- API_AutoFramework_Demo(failed) -->
    </suite> <!-- Failed suite [Default Suite] -->
</testng-results>
